language: python
services:
  - docker
python:
  - "3.6"
stages:
    - before_install
    - install
    - name: after_success
      if: branch = master
before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
script:
  - echo "No script"
install:
  - docker build -t j6mes/docker-base-image .
  - docker tag j6mes/docker-base-image j6mes/docker-base-image:build-$TRAVIS_BUILD_NUMBER
  - docker push j6mes/docker-base-image:build-$TRAVIS_BUILD_NUMBER
after_success:
  - docker tag j6mes/docker-base-image j6mes/docker-base-image:latest
  - docker push j6mes/docker-base-image:latest
  - echo "Done"
